---
- name: Pull Docker Image From DockerHub
  hosts: 192.168.0.255
  remote_user: harsh
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "abhisheksharma402/calculator:version2.0"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Request
      debug:
        var: docker_pull_result

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Running Container
      shell: /usr/bin/docker run --name calc -it -d abhisheksharma402/calculator:version2.0
